## SLAM parameters
Results:
  save_results: True
  save_dir: "results"
  save_trj: False
  save_trj_kf_intv: 5
  use_gui: True
  eval_rendering: True
  use_wandb: False

Dataset:
  type: 'deform'
  sensor_type: 'depth'
  pcd_downsample: 512
  pcd_downsample_init: 32
  adaptive_pointsize: True
  point_size: 0.01
  single_thread: True
  has_gtpose: False
  Calibration:
    fx: 318.5
    fy: 318.2
    cx: 316.8
    cy: 186.3
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    distorted: False
    width: 640
    height: 360
    depth_scale: 1000.0

Training:
  #Initialization
  init_itr_num: 1000
  init_gaussian_update: 100
  init_gaussian_reset: 500
  init_gaussian_th: 0.005
  init_gaussian_extent: 30
  # Tracking and Mapping
  tracking_itr_num: 100
  mapping_itr_num: 10
  gaussian_update_every: 150
  gaussian_update_offset: 50
  gaussian_th: 0.7
  gaussian_extent: 1.0
  gaussian_reset: 2001
  size_threshold: 20
  kf_interval: 5
  window_size: 8
  pose_window: 3
  edge_threshold: 1.1
  rgb_boundary_threshold: 0.01
  alpha: 0.9
  kf_translation: 0.08
  kf_min_translation: 0.05
  kf_overlap: 0.9
  kf_cutoff: 0.3
  prune_mode: 'slam'
  spherical_harmonics: False
  lr:
    cam_rot_delta: 0.003
    cam_trans_delta: 0.001
  4dtam:
    is_2dgs: True
    is_deform: True
    use_normal: True
    add_rigidity: True
    arap:
      radius: 0.05
      num_knn: 20
      subsample_num: 4000
      weight_exp: 100
      weight: 5.0
    lr:
      normal_loss: 0.001
    kf_policy: '4dtam'
    kf_interval: 1



## 3DGS default parameters
opt_params:
  iterations: 30000
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.001
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002

model_params:
  sh_degree: 0
  source_path: ""
  model_path: ""
  resolution: -1
  white_background: False
  data_device: "cuda"

pipeline_params:
  convert_SHs_python: False
  compute_cov3D_python: False
